version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm uninstall react-scripts
      - npm install react-scripts
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: yes
