name: Deploy to AWS

on: [push, pull_request] # Trigger the workflow on push or pull request events

jobs:
  website-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
      
      - name: Build and Deploy to AWS S3
        run: |
          echo "Building the project..."
          npm run build
          echo "Deploying to AWS S3..."
          aws s3 sync build/ s3://nandinibhatt.me/ --delete --acl public-read
          aws cloudfront create-invalidation --distribution-id E1JHKWLDY7Q5ZL --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Notify on Failure
        if: failure() # Execute only if previous steps failed
        run: |
          aws sns publish --topic-arn arn:aws:sns:us-east-2:975050059984:codestar-notifications- --message "Your portfolio deployment has failed."
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
